


[sample]
  name = "aaaaa"

[path]
    config = "C:\\PersonalWorks\\Quela\\QM\\QMtest\\QMtest.json"
    dynamic_config = "C:\\PersonalWorks\\Quela\\QM\\QMtest\\QMtest_config.pkl"
    specification = "C:\\PersonalWorks\\Quela\\QM\\QMtest\\QMtest_spec.pkl"
    output_root = "C:\\PersonalWorks\\Quela\\QM\\QMtest"

