


[sample]
  name = "HappyQubit"

[path]
    config = "C:\\Users\\arthu\\Coding\\Python\\Single_Qubit_Measurement_config\\HappyQubit.json"
    dynamic_config = "C:\\Users\\arthu\\Coding\\Python\\Single_Qubit_Measurement_config\\HappyQubit_config.pkl"
    specification = "C:\\Users\\arthu\\Coding\\Python\\Single_Qubit_Measurement_config\\HappyQubit_spec.pkl"
    output_root = "C:\\Users\\arthu\\Coding\\Python\\Single_Qubit_Measurement_config\\HappyQubit"


